### ISSUE TITLE
Early Project TODO's and Planning

### ISSUE THREAD

**Issue by Hexx13** [Hexx13/Hex-Music-Store#1]
### TODO's
- [x] Add valid redirect after successful login
- [x] Create registration page for users
    - [x] Styles
    - [x] Customize code
- https://symfonycasts.com/screencast/symfony-security/registration-auth
- [x] Add roles apart from User & Admin
   - Student?
   - Contractor/Luthier/Employee?
   - Teacher?
- [x] #9

- [ ] Add rememberMe to login

- [x] implement latest bootstrap 

- [x] add responsive nav

### Ideas for pages
- Store catalog page/Online Store
- Lesson booking
- Contractors for instrument set-up/repair/custom builds
- Contact/Location 
- Account
